### PR TITLE
Implement Redis + Setup testing fixtures

### PR DESCRIPTION
**Pull request by AndreasPB**
* Needs a library that is build on Pydantic

### CODE REVIEW

**Comment by AndreasPB** [comment]
Chose Redis because it makes a lot of sense for the use case :DD

Using an async Redis/Pydantic library called `pydantic_aioredis` that seems to work well with FastAPI

GL with the review :dancers:

**Comment by AndreasPB** [comment]
Did a bunch of tests + Refactored some stuff

**Comment by AndreasPB** [comment]
Setup the Class models(still hate that we use `Class` as a name BTW) + test fixtures

**Review by nullxDEADBEEF — CHANGES_REQUESTED** [review]
Would be awesome to have the statistic tests in a subfolder,
so we get /tests/statistics/test_class_statistics.py for example

**Comment by AndreasPB** [comment]
Done, I think

**Review by nullxDEADBEEF — APPROVED** [review]
LGTM might want @Pankai222 to verify as well to make sure the SQL part matches

**Review by Primdahl26 — APPROVED** [review]

**Review by Pankai222 — APPROVED** [review]

**Pull request merged**
