### PR TITLE
Random token generator endpoint

### PR DESCRIPTION
**Pull request by nullxDEADBEEF**
We need to generate random tokens to that the lecturer will generate for the students to register their attendance

### CODE REVIEW

**Comment by AndreasPB** [comment]
Just a reminder, you don't need to implement it here #15

**Comment by AndreasPB** [comment]
And another reminder for later #16

**Review by AndreasPB — CHANGES_REQUESTED** [review]
Aight... I'm gonna say it... Could you make a test? :D

**Comment by nullxDEADBEEF** [comment]
> Aight... I'm gonna say it... Could you make a test? :D

I'll take a look at it :D

**Review by AndreasPB — CHANGES_REQUESTED** [review]
Needs to be added to CI 🗡️😨

**Review by AndreasPB — APPROVED** [review]
:shipit:

**Pull request merged**
